#!/bin/bash

. $HOME/.config/admiral.d/config
networkIcon=""

if ping -c 1 google.com >> /dev/null 2>&1; then
	echo "%{F$GREEN}${networkIcon} %{F$FG}Online "
else
	echo "%{F$BWHITE}${networkIcon} %{F$FG}Offline "
fi	
