#!/bin/sh

. $HOME/.config/admiral.d/config

# Panel 
PW=180
PH=68
PX=1175
PY=47


n30f -d -x 1175 -y 36 $HOME/.config/admiral.d/popups/power/bg.png &


echo "  %{F$RED}%{F-} %{A:s:}Suspend%{A}  %{F$GREEN} %{F-}%{A:l:}Lock%{A}  %{F$BLUE} %{F-}%{A:e:}Exit%{A}" | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT3" -B "$BG" -F "$FG" -dp | \
    while :; do
        read line
        case $line in 
            'e')
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p 
                exit 
                ;;
            'l')
                i3lock-fancy &
                p=$(pgrep -n lemonbar)
                n=$(pgrep -n n30f)
                kill $n
                kill $p 
                exit                
                ;;
            's')
                sudo /usr/bin/systemctl suspend
                exit
                ;;
        esac
    done
