#!/usr/bin/env bash

. $HOME/.config/admiral.d/config

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null


$HOME/.local/bin/admiral | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT2" -f "$FONT3" -B "$BBLACK" -F "$WHITE" -p -d -b | sh &
. $HOME/.config/admiral.d/topbar
