#!/bin/sh
# A simple Todo List using notify-send

image='/home/mohabaks/Pictures/notify/todo/hello.png'

notify-send  -i $image "

<span foreground='#b16286'>Todo Weekday</span>
<span foreground='#689d6a'>============</span>
<span foreground='#ebdbb2'>
  1. Crypto
  2. HackArt
  3. FinalProject
  4. PracticalVim
</span>

"
