#!/bin/sh
# A simple Todo List using notify-send

image='/home/mohabaks/Pictures/notify/todo/hello.png'

notify-send  -i $image "

<span foreground='#268bd2'>Todo Weekday</span>
<span foreground='#cb4b16'>============</span>
<span foreground='#657b83'>
1. ClassW  2hr
2. Crypto  2hr
3. MathCS  2hr
4. ModernC 2hr
5. CompOrg 2hr
</span>
"
