#!/bin/bash
#
# mohabaks, 21 Oct 2016 22:36
# https://github.com/mohabaks
# Lemonbar Configs
#

# Panel 
PW=1346  
PH=20    
PX=10     
PY=9 

# Fonts
FONT1="-*-tewi-medium-r-*-*-11-*-*-*-*-*-iso10646-*"
FONT2="FontAwesome:size=8"


# Color directory
CD="$HOME/.colors/solarized.dark"

# Fetch the Colors
BG=`cat ${CD} | grep -i background: | tail -c 8`
FG=`cat ${CD} | grep -i foreground: | tail -c 8`

BLACK=`cat ${CD} | grep -i color0: | tail -c 8`
BBLACK=`cat ${CD} | grep -i color8: | tail -c 8`

RED=`cat ${CD} | grep -i color1: | tail -c 8`
BRED=`cat ${CD} | grep -i color9: | tail -c 8`

GREEN=`cat ${CD} | grep -i color2: | tail -c 8`
BGREEN=`cat ${CD} | grep -i color10: | tail -c 8`

YELLOW=`cat ${CD} | grep -i color3: | tail -c 8`
BYELLOW=`cat ${CD} | grep -i color11: | tail -c 8`

BLUE=`cat ${CD} | grep -i color4: | tail -c 8`
BBLUE=`cat ${CD} | grep -i color12: | tail -c 8`

MAGENTA=`cat ${CD} | grep -i color5: | tail -c 8`
BMAGENTA=`cat ${CD} | grep -i color13: | tail -c 8`

CYAN=`cat ${CD} | grep -i color6: | tail -c 8`
BCYAN=`cat ${CD} | grep -i color14: | tail -c 8`

WHITE=`cat ${CD} | grep -i color7: | tail -c 8`
BWHITE=`cat ${CD} | grep -i color15: | tail -c 8`
