#!/bin/bash
#

. $HOME/.config/admiral.d/config

if [[ -d /sys/class/power_supply/BAT1 ]]; then

        batteryState=$(cat /sys/class/power_supply/BAT1/status)
        batteryPower=$(cat /sys/class/power_supply/BAT1/capacity)

        # Determine battery icon based on capacity and state.
        if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
            batteryIcon=""
            batteryColor=${BLACK}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 40 ]]; then
            batteryIcon=""
            batteryColor=${BBLACK}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 60 ]]; then
            batteryIcon=""
            batteryColor=${BBLACK}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 80 ]]; then
            batteryIcon=""
            batteryColor=${BBLACK}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 100 ]]; then
            batteryIcon=""
            batteryColor=${BBLACK}
        else
            batteryIcon=""
            batteryColor=${BBLACK}
        fi
        echo "%{B$GREEN} %{F$batteryColor}${batteryIcon} %{B-} %{F$FG}Battery: ${batteryPower}% "
    else
        echo "%{F$red}No Battery Detected "
fi	
