#!/usr/bin/env bash
# top-panel for minor info
# Date: Sat 17 Dec 2016 22:21

# %{+u},%{-u}

. $HOME/.config/admiral.d/config

kernel(){
    . $HOME/.config/admiral.d/kernel
}

mail(){
   . $HOME/.config/admiral.d/mail 
}

updates(){
  . $HOME/.config/admiral.d/updates 
}

packages(){
 . $HOME/.config/admiral.d/packages 
}

vol(){
  . $HOME/.config/admiral.d/vol 
}

ram(){
 . $HOME/.config/admiral.d/ram 
}

uptime(){
 . $HOME/.config/admiral.d/uptime 
}

net(){
 . $HOME/.config/admiral.d/net 
}

temp(){
   . $HOME/.config/admiral.d/temp 
}

while :;do
        echo " %{l}$(updates)$(packages) %{c}$(mail)$(vol)$(ram)$(temp)$(uptime) %{r}$(net) "
        sleep .5
done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT2" -f "$FONT3" -f "Symbola-8" -B "$BG" -F "$BBLACK" -u 3 -p -d -b | \
while :; do read line; eval $line; done &
