#!/usr/bin/env bash
# top-panel for minor info
# Date: Sat 17 Dec 2016 22:21

# %{+u},%{-u}

. $HOME/.config/admiral.d/config

kernel(){
    . $HOME/.config/admiral.d/kernel
}

mail(){
   . $HOME/.config/admiral.d/mail 
}

music(){
  . $HOME/.config/admiral.d/music
}

music_control(){
echo "%{F#928374}%{A:mpc prev &> /dev/null:}%{A}%{A:mpc play &> /dev/null:}%{A}%{A:mpc pause &> /dev/null:}%{A}%{A:mpc next &> /dev/null:}%{A} "

}

updates(){
  . $HOME/.config/admiral.d/updates 
}

packages(){
 . $HOME/.config/admiral.d/packages 
}

vol(){
  . $HOME/.config/admiral.d/vol 
}

ram(){
 . $HOME/.config/admiral.d/ram 
}

uptime(){
 . $HOME/.config/admiral.d/uptime 
}

net(){
 . $HOME/.config/admiral.d/net 
}

bat(){
 . $HOME/.config/admiral.d/battery
}

temp(){
   . $HOME/.config/admiral.d/temp 
}

clock(){
 . $HOME/.config/admiral.d/clock
}

while :;do
        echo " %{l} $(kernel) %{c}$(clock) %{r}$(mail)$(ram)$(temp)$(net)$(bat) "
        sleep 20
done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT3" -f "$FONT1" -f "$FONT2" -B "$BG" -F "$BBLACK" -u 3 -p | \
while :; do read line; eval $line; done &
