#!/bin/bash
#

. $HOME/.config/admiral.d/config
msg=`python ~/.local/bin/gmail.py`
if [[ $msg =~ .*0.*  ]] || [[ $msg == '' ]]
then
     echo "%{B$BLACK} %{F$BYELLOW} %{B-}%{F$FG} ${msg} "
else
     echo "%{B$BLACK} %{F$YELLOW} %{B-}%{F$FG} ${msg} "
fi
