#!/bin/bash

. $HOME/.config/admiral.d/config
msg=`python ~/.local/bin/gmail.py`
if [[ $msg =~ .*0.*  ]] || [[ $msg == '' ]]
then
     echo "%{F$FG}%{F$MAGENTA} Mail: ${msg} "
else
     echo "%{F$FG}%{F$RED} Mail: ${msg} "
fi
