#!/bin/bash

. $HOME/.config/admiral.d/config
msg=`python ~/.local/bin/gmail.py`
if [[ $msg =~ .*0.*  ]] || [[ $msg == '' ]]
then
     echo "%{F$MAGENTA}%{F$FG} ${msg} "
else
     echo "%{F$RED}%{F$FG} ${msg} "
fi
