#! /usr/bin/bash

. $HOME/.config/admiral.d/config

# Initialize variables
mpc_status=$(mpc current)
mpc_paused=$(mpc status | grep paused)
music_icon=""
artist=$(mpc -f %artist% current)
artist_s=${artist:0:20}
musicname=$(mpc -f %title% current)
musicname_s=${musicname:0:30}

if [[ "$mpc_status" != "" ]]; then
        if [[ "$artist" == "" || "$musicname" == "" ]]; then
                echo "%{F$BLUE}$music_icon Unknown-Artist "
        else
                echo "%{F$CYAN}$music_icon %{F$BLUE}${artist_s} %{F$BBLACK}- %{F$MAGENTA}${musicname_s} "
        fi
else
        echo "%{F$BBLACK}$music_icon ..:Stopped:.. "
fi
