#!/bin/bash

. $HOME/.config/admiral.d/config
networkIcon=""

if ping -c 1 google.com >> /dev/null 2>&1; then
	echo "%{F$FG}${networkIcon}%{F$BLUE} Signal: Online "
else
	echo "%{F$FG}${networkIcon}%{F$FG} Signal: Offline "
fi	
