#!/bin/bash
#

. $HOME/.config/admiral.d/config
ram=$(free -m | awk 'NR==2{printf "%s/%sMB", $3,$2}')

if [[ ${ram%/*} -gt 1000 ]];then

        echo "%{F$RED} %{F$BLACK}%{B$BLACK} %{F$FG}$ram %{B-}%{F$BLACK} "
else
        echo "%{F$BBLACK} %{F$BLACK}%{B$BLACK} %{F$FG}$ram %{B-}%{F$BLACK} "
fi
