#! /usr/bin/env bash

. $HOME/.config/admiral.d/config

temp=$(cat /sys/class/hwmon/hwmon0/temp1_input)

new_temp=$(( temp / 1000 ))

if [[ new_temp -gt 80 ]]; then
        echo "%{F$RED} %{F$BRED}$new_temp°C "
else
         echo "%{F$BBLACK} %{F$BBLACK}$new_temp°C "
fi
