#!/bin/bash

. $HOME/.config/admiral.d/config

# Get AUR updates
# cower -u | wc -l

# Get pacman updates
pm=`pacman -Qqu | wc -l`

if [[ $pm -eq 0 ]]; then
   echo "%{F$BBLACK} %{F$BBLACK}$pm "
else
   echo "%{F$CYAN} %{F$CYAN}$pm "
fi
