#!/bin/bash

. $HOME/.config/admiral.d/config

# Get AUR updates
# cower -u | wc -l

# Get pacman updates
pm=`pacman -Qqu | wc -l`

if [[ $pm -eq 0 ]]; then
   echo " %{F$BBLACK} %{F$BLACK}%{B$BLACK} %{F$FG}$pm %{B-}%{F$BLACK}"
else
   echo " %{F$BBLACK} %{F$BLACK}%{B$BLACK} %{F$FG}$pm %{B-}%{F$BLACK} "
fi
